version: '3.3'
services:
  chat-command:
    build: chat-command
    ports:
      - "8081:8081"
    expose:
      - '8081'
    environment:
      MYSQL_HOST: mysqlserver
      AXON_HOST: axonserver
    depends_on:
      - mysqlserver
    networks:
      - web
      - db-mysql
      - axon
  chat-query:
    build: chat-query
    ports:
      - "8080:8080"
    expose:
      - '8080'
    environment:
      MYSQL_HOST: mysqlserver-slave
      AXON_HOST: axonserver
    depends_on:
      - mysqlserver-slave
    networks:
      - web
      - db-mysql-slave
      - axon

  mysqlserver:
    image: mysql:5.7
    hostname: mysqlserver
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: '1234qwer'
      MYSQL_ROOT_PASSWORD: '1234qwer'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - db-mysql:/var/lib/mysql
    networks:
      - db-mysql

  mysqlserver-slave:
    image: mysql:5.7
    hostname: mysqlserver-slave
    restart: always
    environment:
      MYSQL_DATABASE: 'db-slave'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: '1234qwer'
      MYSQL_ROOT_PASSWORD: '1234qwer'
    ports:
      - '3307:3306'
    expose:
      - '3307'
    volumes:
      - db-mysql-slave:/var/lib/mysql
    networks:
      - db-mysql-slave

  axonserver:
    image: axoniq/axonserver
    hostname: axonserver
    volumes:
      - axonserver-data:/data
      - axonserver-events:/eventdata
      - axonserver-config:/config:ro
    ports:
      - '8024:8024'
      - '8124:8124'
      - '8224:8224'
    networks:
      - axon

volumes:
  db-mysql:
  db-mysql-slave:
  axonserver-data:
  axonserver-events:
  axonserver-config:

networks:
  axon:
  db-mysql:
  db-mysql-slave:
  web: